### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by The-Futurist** [dg9ngf/NetRevisionTool#13]
Ocassionally when I do a build, I see the version message in the final DLL indicating there were uncommitted changes, but no changes were pending.

It seems that sometime NetRevisionTool/Git see the modified AssemblyInfo.cs file and backup and for a brief interval detect uncommitted changes, once the build is done these revert by themselves and there are no changes.

**Comment by ygoe** [comment]
Did you cancel the build any time around when this happened? Cancelling the build will leave modified and backup files. The next build should then pick them up and clean up again.

Also, if you use NetRevisionTool through pre/post build events in multiple projects of a solution and build the solution with parallel build enabled, this might happen when one NetRevisionTool-started Git sees the temporary files of the other project's instance. You could disable parallel build (MSBuild /m) to see if that helps. I have my own solution ([PowerShell build framework](https://github.com/ygoe/psbuild)) for this case.

**Comment by The-Futurist** [comment]
@ygoe - I'm wondering if there's a neater way. I agree this is a side effect of parallel builds running. So perhaps it's a good idea that when the tool detects uncommitted changes it could look to see if the files involved are name AssemblyInfo.cs or AssemblyInfo.bak and if so, disregard this?

**Comment by ygoe** [comment]
Does the [.NET Revision Task for MSBuild](https://github.com/ygoe/NetRevisionTask) resolve this for you? It's patching the AssemblyInfo file into the obj\ directory and uses that file for the build instead of the original file. This directory should be ignored by Git and so the code isn't modified by patching that file. As a side effect, no more restoring is required after the build and you can now safely interrupt the build without needing to clean up the backup files.
