### ISSUE TITLE
Exited with code 100

### ISSUE THREAD

**Issue by Daaell** [dg9ngf/NetRevisionTool#19]
Error MSB3073: The command ""E:\C#\VS2012\<project name>\_scripts\bin\NetRevisionTool.exe" /patch "E:\C#\VS2012\<project name>\<project name>\"" exited with code 100. (1, 1)

Recently at my work machine i get this error, and looks like i can't even fix it anymore. Previously, and occasionally this error popped up, but all i had to do is to reset 'AssemblyInfo.cs' in git, and everything built after that. 

But right now, this don't seems to help. Even more interesting is that the same solution at home (everything is the same) builds just fine. Also this is not limited to this solution, everything else that uses NRT fails now. 

I'm using NRT as pre/post build, Run the post-build event is on Always.

**Comment by ygoe** [comment]
Could it be a space somewhere in the path of your project directory? I've had that report recently. Renaming the project directory (and all parents) so that they have no space in them resolved it for them.

BTW, you could try the newer [.NET Revision Task for MSBuild](https://github.com/ygoe/NetRevisionTask) that should be more robust than the external tool method.

**Comment by S0und** [comment]
Using NetRevisionTask finally hinted on my original issue. NRT stopped with an error: "Illegal character in Path". Basically there was a corrupt path in environment path. If you have this issue check both user and system path.
