### ISSUE TITLE
Ability to get serial number

### ISSUE THREAD

**Issue by h-h-h-h** [dg9ngf/NetRevisionTool#3]
Hello,

it would be a great addition to be able to get an auto-increased serial number. A possible format for this is:
`[assembly: AssemblyInformationalVersion("1.5.{sernum:1250}-{chash:6}")]`

On execution of NetRevisionTool ...
1. the number is increased,
2. `1.5.1251-abcdef` is used for compilation
3. and `1.5.{sernum:1251}-{chash:6}` is written to the original file.

When the increased number is greater than 65535, it is automatically reset to 1 (or 0?).

**Comment by ygoe** [comment]
The whole purpose of NetRevisionTool is to not touch the file at all when compilation is finished so that no changes appear to the version control. You are proposing to break this rule and make permanent changes to the file.

Also, this would lead to different versions each time you build the project, which can be as often as you want. I perform builds every now and then during coding to check where new errors appear. I also build automatically before committing. The version number would then no longer deterministically depend on the source, time or history alone. Separate build servers that only check out a read-only copy of the source would add their share of the confusion to it.

If this would be implemented, additional care must be taken of the current file encoding. Since this is not relevant for the build process, the temporarily modified files may use a different encoding than the original source file. This would be another change that's exposed to version control. Albeit probably only once.

**Comment by h-h-h-h** [comment]
> this would lead to different versions each time you build the project

My point is:
- Build counts are common for version strings
- A user sees whether a successive version is available without the need for the developer to care about small third-place version number changes

If you <q>build automatically before committing,</q> a change happening before the commit wouldn't be bad. Sure, in other cases a developer would have to remember the `{sernum:...}` setting and take it into account for the workflow.

> If this would be implemented

Are you unsure whether to do it or not?

**Comment by ygoe** [comment]
> Build counts are common for version strings

Yes, and most of them depend on the date.

> without the need for the developer to care about small third-place version number changes

This is in fact all NetRevisionTool exists for. And it provides plenty of methods to do just that. For example a time-based number in several formats, or a commit counter (similar to SVN revision number), or a build/commit date in several formats. Did you notice those? All of them work non-destructive by deriving the version information only from their environment without changing the environment.

> Are you unsure whether to do it or not?

Yes I am.

**Comment by h-h-h-h** [comment]
> For example a time-based number in several formats, or a commit counter (similar to SVN revision number), or a build/commit date in several formats. Did you notice those?

Yes. There are already good options! I'll see whether time-based values are also okay for me.
