### ISSUE TITLE
Create additional file instead of patching AssemblyInfo.cs

### ISSUE THREAD

**Issue by xmedeko** [dg9ngf/NetRevisionTool#5]
Idea is, that the template is in the `AssemblyInfo.cs` commented out by `//`, e.g.

``` csharp
/// template: [assembly: AssemblyInformationalVersion("1.0.{revnum} {c:ymd-}")]
```

The `NetRevisionTool.exe` will create a new file `AssemblyInfoGenerated.cs`:

``` csharp
[assembly: AssemblyInformationalVersion("1.39.50_a34fd2")]
```

The user has to include the `AssemblyInfoGenerated.cs` into the build process, but exclude it from VCS control (`.gitignore`).

The main advantage is, that it does **not need /restore**.

**Comment by ygoe** [comment]
Sounds interesting, I'll think about it.

Did I understand that correctly that the AssemblyInfo.cs does not contain any of the generated attributes but only a template of how they should be generated, then a non-versioned file is generated and included in the project that will only contain those attributes?

That means that the project won't compile without running NetRevisionTool because this will make the source code complete by creating the "missing" file. But I see how the restore would not be necessary anymore.

Out of curiosity: Are you experiencing any issues with restoring after build?

**Comment by xmedeko** [comment]
Yes, you understand it well. Then you have to run the NetRevisionTool first time to compile the project. If you fail to run the NetRevisionTool after that (by any reason), the project compile, but the informations in the generated file would be obsolete.

We have own tool, made in the Powershell, plugged into one project this way and it performs well. I like the NetRevisionTool more, so I am trying it on another project.

I my experience, it's good to have tools which do not require any cleaning after the use. I do not have issues with restoring NetRevisionTool right now. Just the NetRevisionTool forces to run Post-build event always. I have some other Post-build event, which could be run on successful build, but running it always does not break the thing.

**Comment by ygoe** [comment]
I recently found another tool distributed as NuGet package that can integrate in the .*proj MSBuild file directly so it doesn't need the Pre/PostBuildEvent (#6). That would free up the PostBuildEvent setting. But of course it still would not clean up if an external build was cancelled by Ctrl+C for example.

**Comment by ygoe** [comment]
[.NET Revision Task for MSBuild](https://github.com/ygoe/NetRevisionTask) does this now. It won't patch the file in-place but write the modified file into obj\ and use that file instead of the original source AssemblyInfo file. .NET Revision Tool (this repo) will probably not receive this feature anymore because it's basically outdated technology and the MSBuild-integrated method is much more elegant and robust (and powerful).
